# Generated by Django 5.2.5 on 2025-09-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_onetimepassword_delete_usermanager"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(default="email", max_length=50),
        ),
    ]
